### ISSUE TITLE
`<module:Mandrill>': uninitialized constant Mandrill::Rails::Application (NameError)

### ISSUE THREAD

**Issue by opkorz** [evendis/mandrill-rails#21]
Hi I'm getting this error after to installing this gem and trying to run the server. I'm quite new to Rails and I've been searching for answers all over the web, but I can't find an exact answer to fix this error. Any kind of help would be so great. Thanks!

**Comment by tardate** [comment]
Hi @opkorz, did you happen to call your rails app 'mandrill'? That's just a wild guess, and I think would cause a conflict like this. 

Other than that, can't really help without more info. e.g. a stack trace, Rails version..

**Comment by tardate** [comment]
@opkorz did you get over the issue? I've going to close this for now, but if you still have issues and can provide more info feel free to reply back and we can re-open.
