### ISSUE TITLE
undefined ignore_unhandled_events!

### ISSUE THREAD

**Issue by apinrdw** [evendis/mandrill-rails#28]
Hello, i got this error on Heroku app.

`Unable to load application: NoMethodError: undefined method ignore_unhandled_events! for InboxController:Class` on starting or restarting the app.

its work if i commend out that method, can help me to solve this?

Ruby 2.2.0
Ruby on Rails 4.2.1

**Comment by prosanelli** [comment]
What version of the gem are u using? That method is in master and not in the latest version yet.

**Comment by apinrdw** [comment]
I am using version `1.1.1`
Oh, if that so this issue can be closed. :smile: 
Sorry for that, i can commend it until the master is released.

**Comment by tardate** [comment]
@prosanelli thanks for doing support;-) @apinrdw this is now released in 1.2.0
