### ISSUE TITLE
Generator not working

### ISSUE THREAD

**Issue by tomdracz** [evendis/mandrill-rails#35]
When trying to run rails g mandrill inbox:

Could not find generator 'mandrill'. Maybe you meant 'mandrill', 'model' or 'mailer'
Run `rails generate --help` for more options.

Generator shows when I run rails g --help but no dice in getting it to work.

**Comment by tardate** [comment]
Hi @tomdracz oops, yes I can reproduce the error with the mandrill-rails-demo.

```
mandrill-rails-demo$ be rails generate mandrill inbox
Could not find generator 'mandrill'. Maybe you meant 'mandrill', 'model' or 'mailer'
Run `rails generate --help` for more options.
```

@brianknight10 can you help?

**Comment by tomdracz** [comment]
@tardate Just added a pull request to fix the issue. Working now and tests are passing fine
